name: Workflow TP3

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main


jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: descargar repositorio
      uses: actions/checkout@v4
      
      - name: intalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Instalar dependencias de front
      working-directory: front
      run: npm ci

    - name: corre Lint
      working-directory: front
      run: npm run lint